apiVersion: batch/v1
kind: Job
metadata:
  name: highlander
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["ls", "/highlander"]
      restartPolicy: Never
