apiVersion: batch/v1
kind: Job
metadata:
  name: italian
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Salve! Come va? MBI"]
      restartPolicy: Never
