apiVersion: batch/v1
kind: Job
metadata:
  name: justice-league
spec:
  activeDeadlineSeconds: 10
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "100"]
      restartPolicy: Never
