apiVersion: batch/v1
kind: Job
metadata:
  name: sleeping-beauty
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "30"]
      restartPolicy: Never
