apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spanish
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "¡Hola! ¿Qué tal? MBI"]
          restartPolicy: Never
