---
apiVersion: v1
kind: Namespace
metadata:
  name: irresponsable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: irresponsable
  name: verde
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: verde
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: verde
    spec:
      containers:
      - image: kodekloud/webapp-color
        imagePullPolicy: Always
        name: verde
        args:
        - "--color"
        - "green"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: irresponsable
  name: servicio-verde
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: verde
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: irresponsable
  name: ingreso-verde
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: impetuosa
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:609465708365:certificate/52b5d43b-95cd-4b3a-b12b-07e456048110
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.tls-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#
spec:
  rules:
    - host: verde.irresponsable.tk
      http:
        paths:
          - path: /*
            backend:
              serviceName: tls-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: servicio-verde
              servicePort: 80
